In [1]:
# print hello world
# ipython 이 백단에서 서버로 실행되고 있음. 

print("hello World!")

hello World!


In [3]:
# import numpy

import numpy

In [4]:
a = 1
b = 2

In [6]:
# 객체 정보 조회

a?

In [7]:
# 객체 정보 조회

print?

In [8]:
# 숫자 계산1
# 주피터 노트북에서 바로 숫자 계산도 가능함.
11000 * 55

605000

In [13]:
# 숫자 계산2 : 앞의 숫자를 _로 받음

_ + 40

605200

In [15]:
%cd D:\PRACTICE

D:\PRACTICE


In [21]:
# Let's check what this file contains.
with open('test.txt', 'r') as f:
    print(f.read())

Hello World!


In [37]:
# 파일 저장 처리 2

%%writefile test2.txt
facebook Innovation Lab python datascience class

SyntaxError: invalid syntax (<ipython-input-37-1da0e127a936>, line 3)

In [25]:
# Let's check what this file contains.
with open('test2.txt', 'r') as f:
    print(f.read())

facebook Innovation Lab python datascience class


In [34]:
# 파이썬 함수(.py) 실행하기

%%writefile add.py
def add(x,y) :
    return x+y

print(add(4,4))

Writing add.py


# Markdown cell

### 타입을 Code 에서 Markdown으로 변경하고 실행해야함

# Heading 1
# Heading 2
## Heading 2.1
## Heading 2.2


### 코드 임베딩

```python
print "Hello World"
```

```javascript
console.log("Hello World")
```

# Markdown cell
### 표 만들기

|      This      |    is     |
| -------------- | --------  |
|   a            | table     |

### LaTeX 수식
### 인라인 수식은 LaTex 코드를 다음과 같이 $로 둘러쌈

$e^{i\pi} + 1 = 0$

### 독립 줄의 수식은 다음과 같이 $$로 둘러쌈

$$e^x=\sum_{i=0}^\infty\frac{1}{i!}x^i$$


In [1]:
# split

" ".join("This string\n\r has many\t\tspaces".split())

'This string has many spaces'

In [2]:
# count : 개수를 리턴해주는 함수

"www.networksciencelab.com".count(".")

2

In [8]:
# 정규 표현식

import re
re.split(r"\W", "Hello, World!")

['Hello', '', 'World', '']

In [9]:
# 파일 이름 매칭
import glob
glob.glob("*.ipynb")

['DataScience_Practice_01.ipynb',
 'Numpy 배열(벡터) 연산 및 모듈 출력, matplitlib 시각화 예제 실습.ipynb',
 '파이썬 기본 핵심 활용 및 데이터 파일 처리 코드 예제.ipynb']

In [10]:
# 데이터 파일 처리
# HTML 파일 처리

from bs4 import 

In [5]:
# NumPy로 배열 다루기

# 배열 만들기

import numpy as np # np라는 이름을 별칭으로 많이 씀

In [4]:
numbers = np.array(range(1, 11), copy=True)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# ones : 1 로 채워진 매트릭스나 array를 만드는 것
ones = np.ones([2,4], dtype=np.float64)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# zeros : 0으로 채워진 매트릭스나 array를 만드는 것
zeros = np.zeros([2,4], dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# empty
# 주의 : 배열의 내용물이 항상 0인 것은 아니다. array 초기화에 사용함

empty = np.empty([2,4], dtype=np.float64)
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
ones.shape # 아직 변환되지 않았다면 원래 모양을 반환한다

(2, 4)

In [11]:
ones.ndim  # len(numbers.shape) 와 같다. 차원의 개수 구할 때 사용

2

In [12]:
zeros.dtype  # 데이터 타입

dtype('float64')

In [13]:
# 일정한 간격으로 배열된 배열 만들기
np_numbers = np.arange(2, 5, 0.25)
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

In [16]:
# 브로드 캐스팅(broadcasting)

a = np.arange(4)
b = np.arange(1, 5)
a

array([0, 1, 2, 3])

In [17]:
a = np.arange(4)
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [18]:
a+b

array([1, 3, 5, 7])

In [19]:
a * 5

array([ 0,  5, 10, 15])

In [20]:
# any() 와 all() 함수는 각각 일부 혹은 모든 배열의 엘리먼트가 True 라면 True를 반환

In [21]:
# nonzero() 함수는 0 이 아닌 값을 반환

In [23]:
# 배열 집계와 정렬하기
# 배열의 집계 값을 반환하는 mean(), sum(), std(), min(), max() 함수 제공

In [25]:
# 배열을 셋처럼 다루기
# 생물 정보학 : 유전자 염기 서열 분석해서
# DNA 뉴클레오티드(DNA의 기본 구성 단위)의 순서를 파악
dna = "AGTCCGCGAATACAGGCTCGGT"
dna_as_array = np.array(list(dna))
dna_as_array

array(['A', 'G', 'T', 'C', 'C', 'G', 'C', 'G', 'A', 'A', 'T', 'A', 'C',
       'A', 'G', 'G', 'C', 'T', 'C', 'G', 'G', 'T'], dtype='<U1')

In [26]:
# Pandas로 데이터 프레임 다루기

import numpy as np
import pandas as pd